---
title: "Toolik Lake & Inlet Stations"
editor: visual
format: dashboard
---

```{r}
#| echo: false
#| output: false

packages <- c("ggplot2","ggtext",
              "plotly","tidyverse")
# Packages loading
invisible(lapply(packages, library, character.only = TRUE))
# Functions --------------------------------------------------------------
source("importCSdata.r")
#-------------------------------------------------------------------------
```

# Lake Station

## Row {.tabset}

```{r}
#| label: get plot for lake station
#| echo: false
#| title: "Met Data"

# p <- readRDS("toolik_lake_station.rds")
# 
#-------------------------------------------------------------------------

logger_file <-   "./current/TlkLakeStn.dat"
#-------------------------------------------------------------------------
logger_data<- logger_file %>% map(function(x) importCSdata(x))
logger_data <- logger_data[[1]] %>%
    arrange(timestamp)
  p1 <- ggplot(logger_data) +
    geom_line(aes(x=timestamp, y=airtc_avg, color = "Air Temperature")) +
    scale_x_datetime()+
    labs(#title ="Air Temperature",
         x = "Date",
         y = "celsius ",
         color = '')+
    theme_bw() 
  
  p2 <- ggplot(logger_data) +
    geom_line(aes(x=timestamp, y=rh_avg, color = "Relative Humidity")) +
    scale_x_datetime()+
    labs(#title ="Relative Humidity",
         x = "Date",
         y = "Percent",
         color = '')+
    scale_color_manual(values = c("Relative Humidity" = "blue"))+
    theme_bw() 
  # Wind sensors
  wp1 <- logger_data %>% select(timestamp,ws_ms_s_wvt) %>%
    gather("key", "value", -timestamp)%>%
    ggplot(data=.,aes(x=timestamp, y = value,color=key)) +
    scale_x_datetime()+
    #coord_cartesian(ylim = c(-15,15)) +
    labs(x = "Date",
         y = "Wind Speed (m/s)",
         color = 'Legend')+
    theme_bw() +
    geom_line(color="red",linewidth=.1)+
    theme(axis.title.y = element_markdown(color = "black", size = 8))
  
  wp2 <- logger_data %>% select(timestamp,winddir_d1_wvt) %>%
    gather("key", "value", -timestamp)%>%
    ggplot(data=.,aes(x=timestamp, y = value)) +
    scale_x_datetime()+
    coord_cartesian(ylim = c(0,360)) +
    labs(x = "Date",
         y = "Wind Direction \nDegrees")+
    theme_bw() +
    geom_point(color="deepskyblue",shape =1)+
    theme(axis.title.y = element_markdown(color = "black", size =8))
  
  p3 <- ggplot(logger_data) +
    geom_line(aes(x=timestamp, y=batt_volt_avg, color = "Battery")) +
    scale_x_datetime()+
    labs(#title ="Toolik Lake Float Station",
         x = "Date",
         y = "volts",
         color = '')+
    coord_cartesian(ylim = c(8,15)) +
    scale_color_manual(values = c("Battery" = "black"))+
    theme_bw() 
  
  #----------------------------------------------------------------------
  # Convert to plotly plots.
  # the dynamicTicks needs to be true for the buttons to show
  # auto range needs to be FALSE for range to work
  
  # set the min and max for the initial x axis display in ggplotly
  min_date <-max(logger_data$timestamp)- lubridate::days(5)
  max_date <-max(logger_data$timestamp)
  
  # Define xaxis options for using a range slider
  xax<- list( 
    autorange=F,
    range= list(min_date, max_date),
    rangeselector = list(
      buttons = list(
        list(count = 1, label = "1 week", strp ="week", stepmode = "backward"),
        list(count = 3, label = "3 mo", step = "month", stepmode = "backward"),
        list(step = "all")
      )),
    rangeslider = list(type = "date", thickness=0.05))
  # Create a list of arguments for the annotation layout to add titles to the subplots
  anno_agr <-list(x = .5,
                  text = "",
                  y = 1,
                  yref = "paper",
                  xref = "paper",
                  xanchor = "center",
                  yanchor = "top",
                  yshift = 20,
                  showarrow = FALSE,
                  font = list(size = 15))
  #---------------------------------------------------------- 
  
  anno_agr$text <- "Air Temperature"  
  p1_p <- ggplotly(p1,dynamicTicks = T) %>% 
    layout(xaxis= xax,
           yaxis =list(fixedrange = FALSE),
           annotations = anno_agr) %>%
    partial_bundle()
  
  anno_agr$text <- "Relative Humidity"
  p2_p <- ggplotly(p2,dynamicTicks = T) %>% 
    layout(xaxis= xax,
           yaxis =list(fixedrange = FALSE),
           annotations = anno_agr) %>%
    partial_bundle()
  
  anno_agr$text <- "Battery"
  p3_p <- ggplotly(p3,dynamicTicks = T) %>% 
    layout(xaxis= xax,
           yaxis =list(fixedrange = FALSE),
           annotations = anno_agr) %>%
    partial_bundle()
  
  anno_agr$text <- "Wind Speed"
  w1_p <- ggplotly(wp1,dynamicTicks = T) %>% 
    layout(xaxis= xax,
           yaxis =list(fixedrange = FALSE),
           annotations = anno_agr) %>%
    partial_bundle()
  
  anno_agr$text <- "Wind Direction"
  w2_p <- ggplotly(wp2,dynamicTicks = T) %>% 
    layout(xaxis= xax,
           yaxis =list(fixedrange = FALSE),
           annotations = anno_agr) %>%
    partial_bundle()
  
 subplot(p1_p,p2_p,w1_p,w2_p, p3_p, nrows=5, shareX = TRUE,titleY = T,
               heights = c(.2,.2,.2,.2,.1))
```

```{r}
#| label: get Tchain plot for lake station
#| echo: false
#| title: "Tchain Data"

# # Palette that is good for color blind
  cbPalette15 <- c("#999999","#68023F","#008169","#EF0096","#00DCB5","#FFCFE2","#003C86","#9400E6","#009FFA","#FF71FD","#7CFFFA","#6A0213","#008607","#F60239","#00E307","#FFDC3D")
  #Order and label the columns by shallow to deep depth.
  tc_order <- c("temp0_avg","temp25_avg","temp50_avg","temp75_avg","temp1_avg","temp2_avg","temp3_avg","temp4_avg","temp5_avg","temp6_avg","temp7_avg","temp8_avg","temp10_avg","temp12_avg","temp15_avg","temp18_avg")
  tc_labels <- c("0m","0.25m","0.5m","0.75m","1m","2m","3m","4m","5m","6m","7m","8m","10m","12m","15m","18m")
  
  tp1 <- logger_data %>% select(timestamp,starts_with("temp")) %>%
    gather("key", "value", -timestamp)%>%
    mutate (key = factor(key, levels = tc_order, labels = tc_labels) )%>%
    ggplot(.,aes(x=timestamp, y = value,color=key)) +
    scale_colour_manual(values=cbPalette15) +
    scale_x_datetime()+
    coord_cartesian(ylim = c(0,15)) +
    labs(#title ="T-chain Temperature",
         x = "Date",
         y = "Celsius ",
         color = 'Legend')+
    theme_bw() +
    geom_line(aes(color = key))
  
  # interactive plotly graph
  
  anno_agr$text <- "T-chain Temperatures"
 ggplotly(tp1,dynamicTicks = T) %>% 
    layout(xaxis= xax,
           yaxis =list(fixedrange = FALSE),
           annotations = anno_agr) %>%
    partial_bundle()
```

# Inlet Station

```{r}
#| label: get plot for inlet station
#| echo: false
#| title: "Inlet Data"


#-------------------------------------------------------------------------

logger_file <-  "./current/TLK_Inlet_CR800.dat"
#-------------------------------------------------------------------------
logger_data<- logger_file %>% map(function(x) importCSdata(x))
logger_data <- logger_data[[1]] %>%
    arrange(timestamp)
  
  #Plots

  # Create 4 plots for the panel
  
 p1 <- ggplot(logger_data) +
    geom_line(aes(x=timestamp, y=lvl_mm, color = "Stage Height")) +
    scale_x_datetime()+
    labs(x = "Date",
         y = "mm ",
         color = '')+
    theme_bw() 
  
  p2 <- ggplot(logger_data) +
    geom_line(aes(x=timestamp, y=temp_c_avg, color = "Water Temperature")) +
    scale_x_datetime()+
    labs(#title ="Toolik Inlet Water Temperature",
         x = "Date",
         y = "celsius ",
         color = '')+
    scale_color_manual(values = c("Water Temperature" = "blue"))+
    theme_bw() 
  
  p3 <- ggplot(logger_data) +
    geom_line(aes(x=timestamp, y=cond_us_avg, color = "Conductivity")) +
    scale_x_datetime()+
    labs(#title ="Toolik Inlet Conductivity",
         x = "Date",
         y = "uS/cm",
         color = '')+
    scale_color_manual(values = c("Conductivity" = "green"))+
    theme_bw() 
  
  p4 <- ggplot(logger_data) +
    geom_line(aes(x=timestamp, y=battv_min, color = "Battery")) +
    scale_x_datetime()+
    labs(#title ="Toolik Inlet",
         x = "Date",
         y = "volts",
         color = '')+
    scale_color_manual(values = c("Battery" = "black"))+
    theme_bw() 
  #----------------------------------------------------------------------
  # Convert to plotly plots.
  # the dynamicTicks needs to be true for the buttons to show
  # auto range needs to be FALSE for range to work
  
  # set the min and max for the initial x axis display in ggplotly
  min_date <-max(logger_data$timestamp)- lubridate::days(5)
  max_date <-max(logger_data$timestamp)
  
  # Define xaxis options for using a range slider
  xax<- list( 
    autorange=F,
    range= list(min_date, max_date),
    rangeselector = list(
      buttons = list(
        list(count = 1, label = "1 week", strp ="week", stepmode = "backward"),
        list(count = 3, label = "3 mo", step = "month", stepmode = "backward"),
        list(count = 6, label = "6 mo", step = "month", stepmode = "backward"),
        list(step = "all")
      )),
    rangeslider = list(type = "date", thickness=0.05))
  # Create a list of arguments for the annotation layout to add titles to the subplots
  anno_agr <-list(x = .5,
                  text = "",
                  y = 1,
                  yref = "paper",
                  xref = "paper",
                  xanchor = "center",
                  yanchor = "top",
                  yshift = 20,
                  showarrow = FALSE,
                  font = list(size = 15))
 #---------------------------------------------------------- 
  
  anno_agr$text <- "Stage Height"  
  p1_p <- ggplotly(p1,dynamicTicks = T) %>% 
    layout(xaxis= xax,
           yaxis =list(fixedrange = FALSE),
           annotations = anno_agr) %>% 
    partial_bundle()
  
  anno_agr$text <- "Water Temperature"  
  p2_p <- ggplotly(p2,dynamicTicks = T) %>% 
    layout(xaxis= xax,
           yaxis =list(fixedrange = FALSE),
           annotations = anno_agr) %>%
    partial_bundle()
  
  anno_agr$text <- "Conductivity"  
  p3_p <- ggplotly(p3,dynamicTicks = T) %>% 
    layout(xaxis= xax,
           yaxis =list(rangemode="nonnegative",
                       fixedrange = FALSE),
           annotations = anno_agr) %>%
    partial_bundle()
  anno_agr$text <- "Battery"  
  p4_p <- ggplotly(p4,dynamicTicks = T) %>% 
    layout(xaxis= xax,
           yaxis =list(fixedrange = FALSE),
           annotations = anno_agr) %>%
    partial_bundle()
  
 subplot(p1_p,p2_p,p3_p,p4_p, nrows=4, shareX = TRUE,titleY = T,
               heights = c(.3,.3,.3,.1))

```
